- menu_name: "Szolgáltatások"

- name: "Kapcsolat"
  url: "/contact/"
  title: "Kapcsolat"

- name: "RSS"
  url: "/feed.xml"
  title: "Iratkozz fel az RSS Feedre!"

# - name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
